### ISSUE TITLE
Site only measures consumption, not waste

### ISSUE THREAD

**Issue by rec** [KrauseFx/whereisfelix.today#3]
There are dozens of charts here about consumption, but none of the report on the waste these activities generate. It would be interesting!

Considering the constant flying, you're almost certainly in the top 1% of carbon dioxide emitters, for example.

**Comment by gersomvg** [comment]
I very much enjoyed scrolling through this website, amazed by the sheer obsession of the author with tracking everything, linking APIs etc.

But at the flight charts I immediately lost interest. I'm here trying to not fly at all, or at least only every few years, and there I see hundreds upon hundreds of flights 😞

All those miles might be for a good cause — who am I to judge — but including carbon stats would at least give the impression that it's a conscious consideration of the author.

**Comment by KrauseFx** [comment]
Thanks everyone, I'll spend some time over the next days to include the CO2 emissions as well. In the mean-time, those are the numbers, generated by [nomadlist](https://nomadlist.com/@krausefx) based on my flights data.

![image](https://user-images.githubusercontent.com/869950/165734091-adb60006-aed6-488b-af1b-dc49134834d7.png)

**Comment by KrauseFx** [comment]
I just pushed https://github.com/KrauseFx/howisFelix.today/commit/91c766b738f724f9f85175f86f790c8290ca222f, you can already see the information on https://howisFelix.today 🚀

**Comment by rec** [comment]
It seems you typically fly about 10,000 km a month except for the pandemic, but this year you're back on track for another 10,000 km a month.

You did however manage to do the equivalent of a round the world trip each year of the pandemic.

----

Like @gersomvg, I gave up flying because of the tremendous devastation that it causes to the planet and to any hope of livable future for humanity.

This extreme level of consumption you display so proudly leaves me sad and horrified in equal measure.

**Comment by gersomvg** [comment]
I'm surprised by you willingness and speed to add this, thank you. 😄  I don't want to get into the realm of judging each other endlessly; in the end I believe most people are willing to make changes and for most it comes in small steps.

To be honest, I expected it to account for more than avg citizen emissions, but within the US this is actually not too much off the charts. I guess part of this is because the US has an average of 14 tonnes/person/year and the Netherlands (where i'm from) only 8 tonnes/person/year. This is still crazy high btw, since the global average is 5 tonnes/person/year. And in 2030 we need to be at zero, with a worldwide budget of max 6 tonnes/person/year until that year (1.5 degrees scenario, this includes any emissions caused indirectly by industry).

Source: https://ourworldindata.org/co2-emissions#per-capita-co2-emissions

**Comment by rec** [comment]
The chart compares the personal CO2 emissions just from flying to the average American CO2 output _from all sources_, so of course the ratio will always be a lot less than 100%.
